#pragma once
#include "sound/SoundSource.h"
enum PlayBgm
{
	BGM_TITLE = 0,
	BGM_STAGE = 1,
	BGM_STAGECLEAR = 2,
	BGM_GAMECLEAR = 3,
	BGM_GAMEOVER = 4,
	BGM_SAD = 5,
	BGM_DESTINY = 6,
	BGM_WELCOME = 7,
	BGM_DISTRUST = 8,
	BGM_TRAIN = 9,
	BGM_HEART = 10,
	BGM_STREET = 11,
	SE_WEIGHTBOARD = 12,
	SE_TEXTBUTTON = 13,
	SE_QUESTION = 14,
	SE_TITLEBUTTON = 15,
	SE_QUESTION2 = 16,
	SE_QUESTION3 = 17,
	SE_ICEWALK = 18,
	SE_IRONBALLPUT = 19,
	SE_IRONBALLGET = 20,
	SE_WALK = 21,
	SE_FALL = 22,
	SE_KAIDAN = 23,
	SE_BUTTON = 24,
	SE_BOXGET = 25
};

class Bgm : public IGameObject
{
public:
	Bgm();
};

